---
- hosts: default
  remote_user: ja
  sudo: yes

  tasks:
  - name: Update
    apt: update_cache=yes
  - name: Install git
    apt: name=git state=present
  - name: Clone 
    shell: rm -rf SMS_Estadisticas && git clone https://github.com/JA-Gonz/SMS_Estadisticas. 
